---
ssh:
  insert_key: false

vms:
  - name: "puppet-master"
    box:  "puppetlabs/centos-7.2-64-nocm"
    roles:
      - setup_control_repo
      - get_modules
      - puppet_master
      - pe-memory-tuning2
      - el-tools
      - el-stop-firewall
      - el-fix-path
      - 4gb-memory
      - base

  - name: "bitbucket"
    box:  "puppetlabs/centos-7.2-64-nocm"
    roles:
      - puppet_agent
      - el-tools
      - el-stop-firewall
      - el-fix-path
      - 2gb-memory
      - 2_cpus
      - base

